# 02 - Data Cleaning

## Objective

The objective of this notebook is to clean the raw stock market datasets before performing exploratory data analysis.

Cleaning Steps:

- Load raw datasets
- Convert Date column
- Check missing values
- Remove missing values
- Remove duplicate rows
- Sort data by Date
- Save cleaned datasets

In [10]:
import os
import sys
from pathlib import Path

import pandas as pd 
    
sys.path.append(os.path.abspath("../src"))

%load_ext autoreload
%autoreload 2

from clean_data import data_cleaning

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
raw_path = Path("../data/raw")
cleaned_path = Path("../data/cleaned")

cleaned_path.mkdir(parents=True, exist_ok=True)

In [12]:
stocks = [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "RELIANCE.NS",
    "TCS.NS",
    "HDFCBANK.NS",
    "INFY.NS"
]

In [13]:
cleaned_data = {}

for stock in stocks:

    input_file = raw_path / f"{stock}.csv"
    output_file = cleaned_path / f"{stock}.csv"

    cleaned_data[stock] = data_cleaning(
        input_file,
        output_file
    )

    print(
        f"{stock}: "
        f"{len(cleaned_data[stock])} rows cleaned and saved."
    )

AAPL: 2945 rows cleaned and saved.
MSFT: 2945 rows cleaned and saved.
NVDA: 2945 rows cleaned and saved.
AMZN: 2945 rows cleaned and saved.
RELIANCE.NS: 2897 rows cleaned and saved.
TCS.NS: 2897 rows cleaned and saved.
HDFCBANK.NS: 2897 rows cleaned and saved.
INFY.NS: 2897 rows cleaned and saved.

## Verify Cleaned Dataset

In [14]:
for stock in stocks:

    df = cleaned_data[stock]

    print(
        f"{stock}: "
        f"{df['Date'].min().date()} → "
        f"{df['Date'].max().date()} | "
        f"{len(df)} rows"
    )

AAPL: 2015-01-02 → 2026-09-18 | 2945 rows
MSFT: 2015-01-02 → 2026-09-18 | 2945 rows
NVDA: 2015-01-02 → 2026-09-18 | 2945 rows
AMZN: 2015-01-02 → 2026-09-18 | 2945 rows
RELIANCE.NS: 2015-01-01 → 2026-09-18 | 2897 rows
TCS.NS: 2015-01-01 → 2026-09-18 | 2897 rows
HDFCBANK.NS: 2015-01-01 → 2026-09-18 | 2897 rows
INFY.NS: 2015-01-01 → 2026-09-18 | 2897 rows

In [15]:
for stock in stocks:

    df = cleaned_data[stock]

    print(f"\n{stock}")
    print("Missing values:", df.isnull().sum().sum())
    print("Duplicate rows:", df.duplicated().sum())
    print("Date dtype:", df["Date"].dtype)

AAPL
Missing values: 0
Duplicate rows: 0
Date dtype: datetime64[ns]

MSFT
Missing values: 0
Duplicate rows: 0
Date dtype: datetime64[ns]

NVDA
Missing values: 0
Duplicate rows: 0
Date dtype: datetime64[ns]

AMZN
Missing values: 0
Duplicate rows: 0
Date dtype: datetime64[ns]

RELIANCE.NS
Missing values: 0
Duplicate rows: 0
Date dtype: datetime64[ns]

TCS.NS
Missing values: 0
Duplicate rows: 0
Date dtype: datetime64[ns]

HDFCBANK.NS
Missing values: 0
Duplicate rows: 0
Date dtype: datetime64[ns]

INFY.NS
Missing values: 0
Duplicate rows: 0
Date dtype: datetime64[ns]

In [16]:
cleaned_data["AAPL"].head()

,Date,Adj Close,Close,High,Low,Open,Volume,Company
0,2015-01-02,24.171762,27.332500,27.860001,26.837500,27.847500,212818400,AAPL
1,2015-01-05,23.490801,26.562500,27.162500,26.352501,27.072500,257142000,AAPL
2,2015-01-06,23.493010,26.565001,26.857500,26.157499,26.635000,263188400,AAPL
3,2015-01-07,23.822430,26.937500,27.049999,26.674999,26.799999,160423600,AAPL
4,2015-01-08,24.737745,27.972500,28.037500,27.174999,27.307501,237458000,AAPL

In [17]:
cleaned_data["AAPL"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2945 entries, 0 to 2944
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2945 non-null   datetime64[ns]
 1   Adj Close  2945 non-null   float64
 2   Close      2945 non-null   float64
 3   High       2945 non-null   float64
 4   Low        2945 non-null   float64
 5   Open       2945 non-null   float64
 6   Volume     2945 non-null   int64
 7   Company    2945 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 184.2+ KB

In [18]:
cleaned_data["AAPL"].describe()

,Date,Adj Close,Close,High,Low,Open,Volume
count,2945,2945.000000,2945.000000,2945.000000,2945.000000,2945.000000,2.945000e+03
mean,2020-11-07 17:15:08.251273472,117.047366,119.519348,120.713434,118.204454,119.403058,1.076627e+08
min,2015-01-02 00:00:00,20.548145,22.584999,22.917500,22.367500,22.500000,1.791060e+07
25%,2017-12-04 00:00:00,37.679626,40.400002,40.930000,40.000000,40.487499,5.990700e+07
50%,2020-11-05 00:00:00,115.904991,119.389999,120.989998,118.000000,119.550003,9.037020e+07
75%,2023-10-11 00:00:00,176.463318,179.289993,180.589996,177.339996,179.279999,1.338384e+08
max,2026-09-18 00:00:00,339.786926,340.079987,344.570007,337.350006,340.029999,6.488252e+08
std,NaN,84.137782,83.640391,84.462623,82.713630,83.529435,6.778726e+07

## Observations

- The Yahoo Finance datasets were already well structured.
- No missing values were found.
- No duplicate records were detected.
- The `Date` column was successfully converted to datetime format.
- The cleaned datasets are ready for exploratory data analysis.